name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache .pnpm-store
        uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install pnpm
        run: curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@6
      - run: pnpm i
      - run: pnpm build
      - run: pnpm type-check
      - run: pnpm lint
      - run: pnpm format
      - name: Sync to glitch
        run: |
          sed "s/dist\///" package.json > dist/package.json
          sed -i '/\"devDependencies\"/,/}/ d; /^$/d' dist/package.json
          ls dist
          cd dist
          git init
          git config user.email "48618675+amrbashir@users.noreply.github.com"
          git config user.name "amrbashir"
          git remote add origin ${{ secrets.GLITCH_GIT_URL }}
          git fetch
          git add .
          git commit -m "init"
          git push -f -u origin master
